[package]
name = "names"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lolcat = "1.5"
colored = "2"
color-eyre = "0.6.2"
